In [1]:
import pandas as pd
import numpy as np

In [2]:
# Define covariance matrices S1 and S2
S1 = np.array([[13825.3, 23823.4],
               [23823.4, 73107.4]])

S2 = np.array([[8632, 19616.7],
               [19616.7, 55964.5]])

print("S1:")
print(S1)
print("\nS2:")
print(S2)

S1:
[[13825.3 23823.4]
 [23823.4 73107.4]]

S2:
[[ 8632.  19616.7]
 [19616.7 55964.5]]


In [3]:
n1=77
n2=77
p=2

In [10]:
(n1-1)+(n2-1)

152

In [8]:
S=(1/((n1-1)+(n2-1)))*((n1-1)*(S1)+(n2-1)*(S2))

In [9]:
S

array([[11228.65, 21720.05],
       [21720.05, 64535.95]])

In [11]:
det_S = np.linalg.det(S)
det_S1 = np.linalg.det(S1)
det_S2 = np.linalg.det(S2)

In [12]:
print("Determinant of S:", det_S)
print("Determinant of S1:", det_S1)
print("Determinant of S2:", det_S2)

Determinant of S: 252891022.96499926
Determinant of S1: 443177349.66000074
Determinant of S2: 98270645.10999995


In [13]:
M=((n1-1)+(n2-1))*np.log(det_S)-(n1-1)*np.log(det_S1)-(n2-1)*np.log(det_S2)
M

29.200866569194204

In [14]:
k=2

In [15]:
1/(n1-1)+1/(n2-1)

0.02631578947368421

In [19]:
1/152

0.006578947368421052

In [18]:
1/((n1-1)+(n2-1))

0.006578947368421052

In [20]:
C_ = 1 - (((2*p**2 + 3*p -1)/(6*(p+1)*(k-1)))*(1/(n1-1)+1/(n2-1)-1/((n1-1)+(n2-1))))

In [21]:
C_

0.9857456140350878

In [22]:
MC=M*C_

In [23]:
MC

28.784626146607007

In [24]:
df=p*(p+1)*(k-1)/2
df

3.0

In [27]:
from scipy.stats import chi2

titik_kritis = chi2.ppf(0.90, df)
titik_kritis

6.251388631170325

In [28]:
print("kesimpulan: ")
if MC>titik_kritis:
    print("Tolak H0, berarti ada perbedaan yang signifikan antara kedua varians")
else:
    print("Gagal tolak H0, berarti tidak ada perbedaan yang signifikan antara kedua varians")

kesimpulan: 
Tolak H0, berarti ada perbedaan yang signifikan antara kedua varians
