In [1]:
import pandas as pd
import numpy as np

In [ ]:
m1 = np.array([[6, 7]])
m2 = np.array([[5, 9]])
m3 = np.array([[4, 6]])
m4 = np.array([[6, 6]])
m5 = np.array([[4, 7]])
m6 = np.array([[5, 4]])
m7 = np.array([[6, 4]])



In [16]:
df = pd.DataFrame({
    'Y1': [6, 5, 4, 6, 4, 5, 6],
    'Y2': [7, 9, 6, 6, 7, 4, 4],
    'Perlakuan': [1, 1, 2, 2, 2, 3, 3]
})

In [17]:
df

Y1  Y2  Perlakuan
0   6   7          1
1   5   9          1
2   4   6          2
3   6   6          2
4   4   7          2
5   5   4          3
6   6   4          3

# SOAL 1

In [22]:
m_rata2_p1 = (m1 + m2) / 2
m_rata2_p2 = (m3 + m4 + m5) / 3
m_rata2_p3 = (m6 + m7) / 2
m_rata_all = (m1 + m2 + m3 + m4 + m5 + m6 + m7) / 7

In [37]:
print("m_rata2_p1:")
print(m_rata2_p1)
print("\nm_rata2_p2:")
print(m_rata2_p2)
print("\nm_rata2_p3:")
print(m_rata2_p3)
print("\nm_rata_all:")
print(m_rata_all)

m_rata2_p1:
[[5.5 8. ]]

m_rata2_p2:
[[4.66666667 6.33333333]]

m_rata2_p3:
[[5.5 4. ]]

m_rata_all:
[[5.14285714 6.14285714]]


# SOAL 3

## A

In [24]:
selisih_p1 = m_rata2_p1 - m_rata_all
selisih_p2 = m_rata2_p2 - m_rata_all
selisih_p3 = m_rata2_p3 - m_rata_all

In [34]:
A1=len(df['Perlakuan'][df['Perlakuan']==1])*selisih_p1*selisih_p1.T
A2=len(df['Perlakuan'][df['Perlakuan']==2])*selisih_p2*selisih_p2.T
A3=len(df['Perlakuan'][df['Perlakuan']==3])*selisih_p3*selisih_p3.T

In [36]:
print("A1:")
print(A1)
print("\nA2:")
print(A2)
print("\nA3:")
print(A3)

A1:
[[0.25510204 1.32653061]
 [1.32653061 6.89795918]]

A2:
[[ 0.68027211 -0.27210884]
 [-0.27210884  0.10884354]]

A3:
[[ 0.25510204 -1.53061224]
 [-1.53061224  9.18367347]]


In [38]:
A=A1 + A2 + A3
print("\nA (Jumlah):")
print(A)


A (Jumlah):
[[ 1.19047619 -0.47619048]
 [-0.47619048 16.19047619]]


## D

In [39]:
selisih_m1=m1-m_rata2_p1
selisih_m2=m2-m_rata2_p1
selisih_m3=m3-m_rata2_p2
selisih_m4=m4-m_rata2_p2
selisih_m5=m5-m_rata2_p2
selisih_m6=m6-m_rata2_p3
selisih_m7=m7-m_rata2_p3

In [40]:
print("Selisih m1:")
print(selisih_m1)
print("Selisih m2:")
print(selisih_m2)
print("Selisih m3:")
print(selisih_m3)
print("Selisih m4:")
print(selisih_m4)
print("Selisih m5:")
print(selisih_m5)
print("Selisih m6:")
print(selisih_m6)
print("Selisih m7:")
print(selisih_m7)

Selisih m1:
[[ 0.5 -1. ]]
Selisih m2:
[[-0.5  1. ]]
Selisih m3:
[[-0.66666667 -0.33333333]]
Selisih m4:
[[ 1.33333333 -0.33333333]]
Selisih m5:
[[-0.66666667  0.66666667]]
Selisih m6:
[[-0.5  0. ]]
Selisih m7:
[[0.5 0. ]]


In [43]:
D= selisih_m1*selisih_m1.T + selisih_m2*selisih_m2.T + selisih_m3*selisih_m3.T + selisih_m4*selisih_m4.T + selisih_m5*selisih_m5.T + selisih_m6*selisih_m6.T + selisih_m7*selisih_m7.T
print("\nD (Jumlah):")
print(D)


D (Jumlah):
[[ 3.66666667 -1.66666667]
 [-1.66666667  2.66666667]]


## A+D

In [44]:
AD= A + D
print("\nA+D:")
print(AD)


A+D:
[[ 4.85714286 -2.14285714]
 [-2.14285714 18.85714286]]


# SOAL 4

In [45]:
detD=np.linalg.det(D)
detAD=np.linalg.det(AD)

print("\nDeterminant D:", detD)
print("Determinant A+D:", detAD)


Determinant D: 6.999999999999998
Determinant A+D: 87.0


In [46]:
wilk=detD/detAD
print("\nWilks' Lambda:", wilk) 



Wilks' Lambda: 0.08045977011494251


In [47]:
cricital_value = (((len(df))-df['Perlakuan'].nunique()-1)/(df['Perlakuan'].nunique()-1))*(1-np.sqrt(wilk))/(np.sqrt(wilk))
print("Critical Value:", cricital_value)

Critical Value: 3.788126862537029


In [48]:
from scipy import stats

f_table = stats.f.ppf(0.95, 4, 6)
print("F-table (α=0.05, df1=4, df2=6):", f_table)

F-table (α=0.05, df1=4, df2=6): 4.533676950275243


In [49]:
#uji wilks' lambda
if cricital_value > f_table:
    print("\nTolak H0: Ada perbedaan yang signifikan antara perlakuan.")
else:
    print("\nGagal Tolak H0: Tidak ada perbedaan yang signifikan antara perlakuan.")


Gagal Tolak H0: Tidak ada perbedaan yang signifikan antara perlakuan.
